"""Canonical protocol and runtime architecture contracts for FactorMiner."""

from __future__ import annotations

from importlib import import_module

__all__ = [
    "DatasetContract",
    "DependenceMetric",
    "DistillStage",
    "DistanceCorrelationMetric",
    "EvaluateStage",
    "EvaluationKernel",
    "FamilyAwareMemoryPolicy",
    "FactorFamily",
    "FactorFamilyDiscovery",
    "FactorLifecycleEvent",
    "FactorLifecycleStore",
    "GenerateStage",
    "IterationPayload",
    "LibraryGeometry",
    "JumpWorthAssessment",
    "assess_llm_jump_worth",
    "FactorAdmissionService",
    "LibraryUpdateStage",
    "LoopStage",
    "KGMemoryPolicy",
    "MemoryPolicy",
    "NoMemoryPolicy",
    "PaperMemoryPolicy",
    "PaperProtocol",
    "PearsonDependenceMetric",
    "PromptContextBuilder",
    "ResearchExtensionService",
    "FamilyContextService",
    "RegimeMemoryService",
    "NonlinearDependenceService",
    "EnsembleMarginalUtilityService",
    "FamilyContextSummary",
    "RegimeMemorySummary",
    "DependenceProfile",
    "EnsembleUtilitySummary",
    "KnowledgeGraphService",
    "OnlineForgettingService",
    "Phase2ComponentFactory",
    "Phase2Components",
    "RegimeAwareMemoryPolicy",
    "RetrieveStage",
    "SpearmanDependenceMetric",
    "build_dependence_metric",
    "build_memory_policy",
    "CycleThemePlan",
    "MECHANISM_FAMILIES",
    "ResearchCyclePlanner",
    "mechanism_family",
    "ResearchAbsorptionService",
    "ResearchArchetype",
    "ResearchNote",
    "read_research_note",
    "EditAwareMemoryPolicy",
    "EDIT_MOTIF_LABELS",
    "DiCoRewardConfig",
    "DiCoRewardResult",
    "RFTExportConfig",
    "RFTExportResult",
    "RFTTrajectoryRecord",
    "RegimeTaskBucket",
    "compute_dico_reward",
    "export_rft_dataset",
    "build_regime_task_bank",
    "RFT_EXPORT_HONESTY",
    "ExternalResearchReceipt",
    "EvidenceTier",
    "RunStatus",
    "DatasetCommitment",
    "ReviewerState",
    "SourceManifestRef",
    "RESEARCH_RECEIPT_LIMITATIONS",
    "derive_release_id",
    "attest_research_receipt",
]

_ATTRIBUTE_MAP = {
    "DatasetContract": ("factorminer.architecture.dataset_contract", "DatasetContract"),
    "DependenceMetric": ("factorminer.domain.dependence", "DependenceMetric"),
    "DistillStage": ("factorminer.architecture.stages", "DistillStage"),
    "DistanceCorrelationMetric": (
        "factorminer.domain.dependence",
        "DistanceCorrelationMetric",
    ),
    "EvaluateStage": ("factorminer.architecture.stages", "EvaluateStage"),
    "EvaluationKernel": ("factorminer.architecture.evaluation_kernel", "EvaluationKernel"),
    "FamilyAwareMemoryPolicy": (
        "factorminer.architecture.memory_policy",
        "FamilyAwareMemoryPolicy",
    ),
    "FactorFamily": ("factorminer.architecture.families", "FactorFamily"),
    "FactorFamilyDiscovery": ("factorminer.architecture.families", "FactorFamilyDiscovery"),
    "FactorLifecycleEvent": ("factorminer.architecture.lifecycle", "FactorLifecycleEvent"),
    "FactorLifecycleStore": ("factorminer.architecture.lifecycle", "FactorLifecycleStore"),
    "GenerateStage": ("factorminer.architecture.stages", "GenerateStage"),
    "IterationPayload": ("factorminer.architecture.stages", "IterationPayload"),
    "LibraryGeometry": ("factorminer.architecture.geometry", "LibraryGeometry"),
    "JumpWorthAssessment": ("factorminer.architecture.geometry", "JumpWorthAssessment"),
    "assess_llm_jump_worth": ("factorminer.architecture.geometry", "assess_llm_jump_worth"),
    "FactorAdmissionService": (
        "factorminer.architecture.library_services",
        "FactorAdmissionService",
    ),
    "LibraryUpdateStage": ("factorminer.architecture.stages", "LibraryUpdateStage"),
    "LoopStage": ("factorminer.architecture.stages", "LoopStage"),
    "KGMemoryPolicy": ("factorminer.architecture.memory_policy", "KGMemoryPolicy"),
    "MemoryPolicy": ("factorminer.architecture.memory_policy", "MemoryPolicy"),
    "NoMemoryPolicy": ("factorminer.architecture.memory_policy", "NoMemoryPolicy"),
    "PaperMemoryPolicy": ("factorminer.architecture.memory_policy", "PaperMemoryPolicy"),
    "PaperProtocol": ("factorminer.architecture.paper_protocol", "PaperProtocol"),
    "PearsonDependenceMetric": ("factorminer.domain.dependence", "PearsonDependenceMetric"),
    "PromptContextBuilder": ("factorminer.architecture.prompt_context", "PromptContextBuilder"),
    "ResearchExtensionService": (
        "factorminer.architecture.research_extensions",
        "ResearchExtensionService",
    ),
    "FamilyContextService": (
        "factorminer.architecture.research_extensions",
        "FamilyContextService",
    ),
    "RegimeMemoryService": (
        "factorminer.architecture.research_extensions",
        "RegimeMemoryService",
    ),
    "NonlinearDependenceService": (
        "factorminer.architecture.research_extensions",
        "NonlinearDependenceService",
    ),
    "EnsembleMarginalUtilityService": (
        "factorminer.architecture.research_extensions",
        "EnsembleMarginalUtilityService",
    ),
    "FamilyContextSummary": (
        "factorminer.architecture.research_extensions",
        "FamilyContextSummary",
    ),
    "RegimeMemorySummary": (
        "factorminer.architecture.research_extensions",
        "RegimeMemorySummary",
    ),
    "DependenceProfile": (
        "factorminer.architecture.research_extensions",
        "DependenceProfile",
    ),
    "EnsembleUtilitySummary": (
        "factorminer.architecture.research_extensions",
        "EnsembleUtilitySummary",
    ),
    "KnowledgeGraphService": ("factorminer.architecture.phase2_services", "KnowledgeGraphService"),
    "OnlineForgettingService": (
        "factorminer.architecture.phase2_services",
        "OnlineForgettingService",
    ),
    "Phase2ComponentFactory": (
        "factorminer.architecture.phase2_services",
        "Phase2ComponentFactory",
    ),
    "Phase2Components": (
        "factorminer.architecture.phase2_services",
        "Phase2Components",
    ),
    "RegimeAwareMemoryPolicy": (
        "factorminer.architecture.memory_policy",
        "RegimeAwareMemoryPolicy",
    ),
    "RetrieveStage": ("factorminer.architecture.stages", "RetrieveStage"),
    "SpearmanDependenceMetric": ("factorminer.domain.dependence", "SpearmanDependenceMetric"),
    "build_dependence_metric": ("factorminer.domain.dependence", "build_dependence_metric"),
    "build_memory_policy": ("factorminer.architecture.memory_policy", "build_memory_policy"),
    "CycleThemePlan": ("factorminer.architecture.research_planner", "CycleThemePlan"),
    "MECHANISM_FAMILIES": ("factorminer.architecture.families", "MECHANISM_FAMILIES"),
    "ResearchCyclePlanner": ("factorminer.architecture.research_planner", "ResearchCyclePlanner"),
    "mechanism_family": ("factorminer.architecture.families", "mechanism_family"),
    "ResearchAbsorptionService": (
        "factorminer.architecture.research_absorption",
        "ResearchAbsorptionService",
    ),
    "ResearchArchetype": (
        "factorminer.architecture.research_absorption",
        "ResearchArchetype",
    ),
    "ResearchNote": ("factorminer.architecture.research_absorption", "ResearchNote"),
    "read_research_note": (
        "factorminer.architecture.research_absorption",
        "read_research_note",
    ),
    "EditAwareMemoryPolicy": (
        "factorminer.architecture.memory_policy",
        "EditAwareMemoryPolicy",
    ),
    "EDIT_MOTIF_LABELS": ("factorminer.architecture.memory_policy", "EDIT_MOTIF_LABELS"),
    "DiCoRewardConfig": ("factorminer.architecture.rft_export", "DiCoRewardConfig"),
    "DiCoRewardResult": ("factorminer.architecture.rft_export", "DiCoRewardResult"),
    "RFTExportConfig": ("factorminer.architecture.rft_export", "RFTExportConfig"),
    "RFTExportResult": ("factorminer.architecture.rft_export", "RFTExportResult"),
    "RFTTrajectoryRecord": ("factorminer.architecture.rft_export", "RFTTrajectoryRecord"),
    "RegimeTaskBucket": ("factorminer.architecture.rft_export", "RegimeTaskBucket"),
    "compute_dico_reward": ("factorminer.architecture.rft_export", "compute_dico_reward"),
    "export_rft_dataset": ("factorminer.architecture.rft_export", "export_rft_dataset"),
    "build_regime_task_bank": ("factorminer.architecture.rft_export", "build_regime_task_bank"),
    "RFT_EXPORT_HONESTY": ("factorminer.architecture.rft_export", "RFT_EXPORT_HONESTY"),
    "ExternalResearchReceipt": (
        "factorminer.architecture.research_receipt",
        "ExternalResearchReceipt",
    ),
    "EvidenceTier": ("factorminer.architecture.research_receipt", "EvidenceTier"),
    "RunStatus": ("factorminer.architecture.research_receipt", "RunStatus"),
    "DatasetCommitment": ("factorminer.architecture.research_receipt", "DatasetCommitment"),
    "ReviewerState": ("factorminer.architecture.research_receipt", "ReviewerState"),
    "SourceManifestRef": ("factorminer.architecture.research_receipt", "SourceManifestRef"),
    "RESEARCH_RECEIPT_LIMITATIONS": (
        "factorminer.architecture.research_receipt",
        "RESEARCH_RECEIPT_LIMITATIONS",
    ),
    "derive_release_id": ("factorminer.architecture.research_receipt", "derive_release_id"),
    "attest_research_receipt": (
        "factorminer.architecture.research_receipt",
        "attest_research_receipt",
    ),
}


def __getattr__(name: str):
    if name not in _ATTRIBUTE_MAP:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attr_name = _ATTRIBUTE_MAP[name]
    module = import_module(module_name)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value
